name: deep_learning
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - altair 
  - vega_datasets
  - python=3.7
  - numpy
  - jupyterlab
  - h5py
  - matplotlib
  - pytorch
  - torchvision
